// imports 
import mongoose from "mongoose"; 

// user data schema 
const userDataSchema = new mongoose.Schema({
    user_name : {
        type : String ,
        required : true ,
    }, 
    user_email : {
        type : String ,
        unique : true ,
        required : true ,
    },
    user_img : {
        type : String ,
        required : true ,
    },
    user_ID : { //User ID will generated by the server with the help of shortid package unique for each user 
        type : String ,
        unique : true ,
    }
}, {timestamps : true}) ;


// user data model
const userData = mongoose.model('userData' , userDataSchema) ;

// exports 
module.exports = { userData };